### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by sanchezcl** [TutorialEdge/Go#5]
Hi, thanks for the awesome tutorials.

I was following your tutorials and when i got to the [advance section ](https://github.com/TutorialEdge/Go#advanced-tutorials) the first link for the "01 - Go Websockets Tutorial" ["Read Tutorial"](https://tutorialedge.net/golang/go-websockets-tutorial/) is broken (https://tutorialedge.net/golang/go-websockets-tutorial/)

Thanks again, and keep going!

**Comment by sanchezcl** [comment]
This is the correct link https://tutorialedge.net/golang/go-websocket-tutorial/

**Comment by elliotforbes** [comment]
Thanks for pointing this out! I've fixed it after long last haha!
